export type Locale = "en" | "es" | "fr" | "pt";

export interface ChatMessage {
  role: "user" | "assistant";
  content: string;
}

export interface DashboardState {
  locale: Locale;
  rightPanelCollapsed: boolean;
  rightPanelMode: "insights" | "chat";
  chatMessages: ChatMessage[];
  isLoadingChat: boolean;
  setLocale: (locale: Locale) => void;
  setRightPanelCollapsed: (collapsed: boolean) => void;
  setRightPanelMode: (mode: "insights" | "chat") => void;
  addChatMessage: (message: ChatMessage) => void;
  setIsLoadingChat: (loading: boolean) => void;
  clearChat: () => void;
}

export interface Translation {
  nav: {
    dashboard: string;
    importsOverview: string;
    totalImports: string;
    hsCodes: string;
    importsByProduct: string;
    importsTimeline: string;
    tradersAndCustoms: string;
    tradersAndCustomsDetailed: string;
    countriesDetailed: string;
    importsByCountry: string;
    importsOperations: string;
    exportsOverview: string;
    totalExports: string;
    exportsByProduct: string;
    exportsTimeline: string;
    exportsByCountry: string;
    exportsOperations: string;
    priceProjection: string;
    dashboardPages: string;
    comingSoon: string;
  };
  eda: {
    title: string;
    subtitle: string;
    cifPriceLine: string;
    cifPriceDistribution: string;
    cifPriceHeatmap: string;
    cifPriceRolling: string;
    cifPriceCandles: string;
    candleOpen: string;
    candleHigh: string;
    candleLow: string;
    candleClose: string;
    candleHint: string;
    volume: string;
    cifPriceMetrics: string;
    externalFeatures: string;
    externalFeaturesExplainer: string;
    product: string;
    frequency: string;
    daily: string;
    monthly: string;
    currentPrice: string;
    meanPrice: string;
    minPrice: string;
    maxPrice: string;
    volatility: string;
    dataPoints: string;
    lastUpdate: string;
    correlations: string;
    corrFx: string;
    corrCorn: string;
    corrSoy: string;
    rollingShort: string;
    rollingMedium: string;
    rollingLong: string;
    heatmapMonth: string;
    heatmapYear: string;
    heatmapValue: string;
    externalFx: string;
    externalCorn: string;
    externalSoy: string;
    externalCif: string;
    noData: string;
    noDataHint: string;
    avgCorrelation: string;
  };
  projection: {
    title: string;
    subtitle: string;
    subTabAnalysis: string;
    subTabForecast: string;
    product: string;
    frequency: string;
    horizon: string;
    model: string;
    daily: string;
    monthly: string;
    allModels: string;
    forecastChart: string;
    modelComparison: string;
    metricsTable: string;
    lastVsProjected: string;
    lastActual: string;
    projectedEnd: string;
    change: string;
    changePct: string;
    p10: string;
    p90: string;
    rmse: string;
    mae: string;
    mape: string;
    weight: string;
    horizonDays: string;
    horizonMonths: string;
    ensemblePrecision: string;
    modelConfidence: string;
    confidenceHigh: string;
    confidenceMedium: string;
    confidenceLow: string;
    uncertainty: string;
    uncertaintyHint: string;
    bandHint: string;
    ensemblePrecisionHint: string;
    modelComparisonHint: string;
    metricsTableHint: string;
    projectedValuesHint: string;
    projectedVariation: string;
    projectedValues: string;
    date: string;
    price: string;
    lowerRange: string;
    upperRange: string;
    confidenceDegradation: string;
    noData: string;
    noDataHint: string;
  };
  filters: {
    title: string;
    category: string;
    countryOfOrigin: string;
    countryOfDestination: string;
    product: string;
    custom: string;
    importer: string;
    exporter: string;
    year: string;
    month: string;
    allMonths: string;
    months: string[];
    yearStart: string;
    yearEnd: string;
    animationSpeed: string;
    all: string;
    search: string;
    apply: string;
    reset: string;
  };
  dashboard: {
    title: string;
    subtitle: string;
    kpiTotalVolume: string;
    kpiTotalRecords: string;
    kpiTotalCif: string;
    kpiCountries: string;
    kpiProducts: string;
    chartImportsByCountry: string;
    chartImportsByCountryRace: string;
    chartImportsByImporterRace: string;
    chartExportsByCountryRace: string;
    chartExportsByImporterRace: string;
    chartVolumeMt: string;
    chartVolumeMtRace: string;
    noData: string;
    totalImportsChart: string;
    totalExportsChart: string;
    cifPriceAvg: string;
    volumeMt: string;
    priceCif: string;
    priceFob: string;
    volume: string;
  };
  panel: {
    insights: string;
    chat: string;
    chatPlaceholder: string;
    send: string;
    generating: string;
    askAboutData: string;
    totalVolume: string;
    topCountry: string;
    topProduct: string;
    yearRange: string;
    open: string;
  };
  common: {
    loading: string;
    error: string;
    retry: string;
    close: string;
    open: string;
    play: string;
    pause: string;
    replay: string;
  };
  placeholder: {
    select: string;
  };
}
