export type Locale = "en" | "es" | "fr" | "pt";

export interface ChatMessage {
  role: "user" | "assistant";
  content: string;
}

export interface DashboardState {
  locale: Locale;
  rightPanelCollapsed: boolean;
  rightPanelMode: "insights" | "chat";
  chatMessages: ChatMessage[];
  isLoadingChat: boolean;
  setLocale: (locale: Locale) => void;
  setRightPanelCollapsed: (collapsed: boolean) => void;
  setRightPanelMode: (mode: "insights" | "chat") => void;
  addChatMessage: (message: ChatMessage) => void;
  setIsLoadingChat: (loading: boolean) => void;
  clearChat: () => void;
}

export interface Translation {
  nav: {
    dashboard: string;
    importsOverview: string;
    totalImports: string;
    hsCodes: string;
    importsByProduct: string;
    importsTimeline: string;
    tradersAndCustoms: string;
    tradersAndCustomsDetailed: string;
    countriesDetailed: string;
    importsByCountry: string;
    importsOperations: string;
    exportsOverview: string;
    totalExports: string;
    exportsByProduct: string;
    exportsTimeline: string;
    exportsByCountry: string;
    exportsOperations: string;
    priceProjection: string;
    dashboardPages: string;
    comingSoon: string;
  };
  eda: {
    title: string;
    subtitle: string;
    cifPriceLine: string;
    cifPriceDistribution: string;
    cifPriceHeatmap: string;
    cifPriceRolling: string;
    cifPriceCandles: string;
    candleOpen: string;
    candleHigh: string;
    candleLow: string;
    candleClose: string;
    candleHint: string;
    volume: string;
    cifPriceMetrics: string;
    externalFeatures: string;
    externalFeaturesExplainer: string;
    product: string;
    frequency: string;
    daily: string;
    monthly: string;
    currentPrice: string;
    meanPrice: string;
    minPrice: string;
    maxPrice: string;
    volatility: string;
    dataPoints: string;
    lastUpdate: string;
    correlations: string;
    corrFx: string;
    corrCorn: string;
    corrSoy: string;
    rollingShort: string;
    rollingMedium: string;
    rollingLong: string;
    heatmapMonth: string;
    heatmapYear: string;
    heatmapValue: string;
    externalFx: string;
    externalCorn: string;
    externalSoy: string;
    externalCif: string;
    noData: string;
    noDataHint: string;
    avgCorrelation: string;
    proteinEconomics: string;
    proteinProduct: string;
    proteinProt: string;
    proteinProtDig: string;
    proteinDigPercent: string;
    proteinUsdPerProt: string;
    proteinUsdPerDigProt: string;
    proteinEq48: string;
    proteinModeAria: string;
    proteinRaw: string;
    proteinDigestible: string;
  };
  projection: {
    title: string;
    subtitle: string;
    subTabAnalysis: string;
    subTabForecast: string;
    product: string;
    frequency: string;
    horizon: string;
    model: string;
    daily: string;
    monthly: string;
    allModels: string;
    forecastChart: string;
    modelComparison: string;
    metricsTable: string;
    lastVsProjected: string;
    lastActual: string;
    projectedEnd: string;
    change: string;
    changePct: string;
    p10: string;
    p90: string;
    rmse: string;
    mae: string;
    mape: string;
    weight: string;
    horizonDays: string;
    horizonMonths: string;
    ensemblePrecision: string;
    modelConfidence: string;
    confidenceHigh: string;
    confidenceMedium: string;
    confidenceLow: string;
    uncertainty: string;
    uncertaintyHint: string;
    bandHint: string;
    ensemblePrecisionHint: string;
    modelComparisonHint: string;
    metricsTableHint: string;
    projectedValuesHint: string;
    projectedVariation: string;
    projectedValues: string;
    date: string;
    price: string;
    lowerRange: string;
    upperRange: string;
    confidenceDegradation: string;
    noData: string;
    noDataHint: string;
  };
  filters: {
    title: string;
    category: string;
    countryOfOrigin: string;
    countryOfDestination: string;
    product: string;
    custom: string;
    importer: string;
    exporter: string;
    year: string;
    month: string;
    allMonths: string;
    months: string[];
    yearStart: string;
    yearEnd: string;
    animationSpeed: string;
    all: string;
    search: string;
    apply: string;
    reset: string;
    monthAbbr: string[];
  };
  traders: {
    importers: string;
    exporters: string;
    customs: string;
    importer: string;
    exporter: string;
    custom: string;
    view: string;
    topBy: string;
    topByPrice: string;
    pivotTitle: string;
    pivotSubtitle: string;
    mapTitle: string;
    mapSubtitle: string;
    loadingBreakdown: string;
    leftVolume: string;
    leftUsd: string;
    toggleView: string;
    toggleMetric: string;
    viewCharts: string;
    viewTable: string;
    viewMap: string;
    loadBreakdownError: string;
    noDataFiltered: string;
    yearSelectorAria: string;
  };
  byProduct: {
    yearComparatorAria: string;
    loadingYears: string;
    titleVolume: string;
    subtitleVolume: string;
    titlePrice: string;
    subtitlePrice: string;
  };
  byCountry: {
    monthsLabel: string;
    yearsLabel: string;
    toggleGranularity: string;
    title: string;
    subtitleYearly: string;
    subtitleMonthly: string;
    noData: string;
    loadingYears: string;
    yearSelectorAria: string;
  };
  countriesDetailed: {
    yearComparatorAria: string;
    loadingYears: string;
    viewPivot: string;
    viewMap: string;
    toggleView: string;
    mapTitle: string;
    pivotTitle: string;
    mapSubtitle: string;
    pivotSubtitle: string;
    loadBreakdownError: string;
    loadingBreakdown: string;
    loadingVolume: string;
    noData: string;
    countryOfOrigin: string;
    countryOfDestination: string;
  };
  pivotTable: {
    headerCountryProduct: string;
    entityProduct: string;
    volShort: string;
    valUsd: string;
    pricePerMt: string;
    total: string;
    heatmapLabel: string;
    heatmapRange: string;
    scrollRight: string;
    scrollTableRight: string;
  };
  decomposition: {
    title: string;
    subtitle: string;
    categoria: string;
    producto: string;
    aduana: string;
    yearLabel: string;
    loadingYears: string;
    yearAria: string;
    moveUpAria: string;
    moveDownAria: string;
    removeAria: string;
    addDimensionAria: string;
    addDimension: string;
    metricLabel: string;
    toggleMetricAria: string;
    resetHierarchy: string;
    activeFilterLabel: string;
    loadingHierarchy: string;
    total: string;
    noValue: string;
    others: string;
    records: string;
    pickParentValueHint: string;
    volumeLabel: string;
  };
  operations: {
    loadingConnections: string;
    loadingHierarchy: string;
    noConnections: string;
    viewHierarchy: string;
    viewMap: string;
    toggleView: string;
  };
  timeline: {
    titleImports: string;
    titleExports: string;
    subtitleRibbon: string;
    titleAccumulatedImports: string;
    titleAccumulatedExports: string;
    subtitleAccumulated: string;
    legendAria: string;
    legendHeader: string;
    noData: string;
  };
  yearSelector: {
    compare: string;
    vs: string;
    year: string;
    yearA: string;
    yearB: string;
  };
  hsCodes: {
    title: string;
    loading: string;
    code: string;
    hsCode: string;
    heading: string;
    product: string;
    category: string;
    industry: string;
    codeType: string;
    rowsCount: string;
    positions: {
      chapter: string;
      heading: string;
      subHeading: string;
      tariffItem: string;
      classificationNumber: string;
    };
  };
  dashboard: {
    title: string;
    subtitle: string;
    kpiTotalVolume: string;
    kpiTotalRecords: string;
    kpiTotalCif: string;
    kpiCountries: string;
    kpiProducts: string;
    chartImportsByCountry: string;
    chartImportsByCountryRace: string;
    chartImportsByImporterRace: string;
    chartExportsByCountryRace: string;
    chartExportsByImporterRace: string;
    chartVolumeMt: string;
    chartVolumeMtRace: string;
    noData: string;
    totalImportsChart: string;
    totalExportsChart: string;
    cifPriceAvg: string;
    volumeMt: string;
    priceCif: string;
    priceFob: string;
    volume: string;
  };
  panel: {
    insights: string;
    chat: string;
    chatPlaceholder: string;
    send: string;
    generating: string;
    askAboutData: string;
    totalVolume: string;
    topCountry: string;
    topProduct: string;
    yearRange: string;
    open: string;
  };
  common: {
    loading: string;
    error: string;
    retry: string;
    close: string;
    open: string;
    play: string;
    pause: string;
    replay: string;
  };
  placeholder: {
    select: string;
  };
}
