const countryToCode: Record<string, string> = {
  argentina: "AR",
  australia: "AU",
  austria: "AT",
  bangladesh: "BD",
  belgium: "BE",
  bolivia: "BO",
  brazil: "BR",
  bulgaria: "BG",
  canada: "CA",
  chile: "CL",
  china: "CN",
  colombia: "CO",
  "costa rica": "CR",
  croatia: "HR",
  cyprus: "CY",
  "czech republic": "CZ",
  czechia: "CZ",
  denmark: "DK",
  "dominican republic": "DO",
  ecuador: "EC",
  egypt: "EG",
  "el salvador": "SV",
  estonia: "EE",
  ethiopia: "ET",
  finland: "FI",
  france: "FR",
  germany: "DE",
  greece: "GR",
  guatemala: "GT",
  honduras: "HN",
  hungary: "HU",
  india: "IN",
  indonesia: "ID",
  ireland: "IE",
  israel: "IL",
  italy: "IT",
  japan: "JP",
  kazakhstan: "KZ",
  kenya: "KE",
  latvia: "LV",
  lesotho: "LS",
  lithuania: "LT",
  luxembourg: "LU",
  malta: "MT",
  mexico: "MX",
  monaco: "MC",
  morocco: "MA",
  netherlands: "NL",
  "new zealand": "NZ",
  nicaragua: "NI",
  nigeria: "NG",
  pakistan: "PK",
  panama: "PA",
  paraguay: "PY",
  peru: "PE",
  philippines: "PH",
  poland: "PL",
  portugal: "PT",
  "puerto rico": "PR",
  romania: "RO",
  russia: "RU",
  "russian federation": "RU",
  slovakia: "SK",
  slovenia: "SI",
  "south africa": "ZA",
  "south korea": "KR",
  "korea, republic of": "KR",
  spain: "ES",
  "sri lanka": "LK",
  sweden: "SE",
  taiwan: "TW",
  thailand: "TH",
  turkey: "TR",
  uganda: "UG",
  ukraine: "UA",
  "united kingdom": "GB",
  "united states": "US",
  usa: "US",
  uruguay: "UY",
  uzbekistan: "UZ",
  venezuela: "VE",
  vietnam: "VN",
  "viet nam": "VN",
  zimbabwe: "ZW",
  oman: "OM",
};

export function getCountryCode(country?: string | null): string | null {
  if (!country) return null;
  const normalized = country.trim().toLowerCase();
  return countryToCode[normalized] || null;
}
