import type { Plan, FaqItem } from "@/interfaces/pricing/interface";

export const plansData: Plan[] = [
  {
    id: "basic",
    name: "Basic",
    desc: "For individual analysts and consultants starting with market intelligence.",
    annual: 1125,
    monthly: 104,
    save: "Save 10% vs monthly",
    feats: [
      { bold: "3", text: " dashboards included" },
      { bold: "1", text: " user seat" },
      { bold: "Extra chart: ", text: "$360", boldEnd: true },
      { text: "Extra user: $800/year" },
      { text: "Max 1 installment" },
      { text: "Mobile app access" },
      { text: "PDF & Excel exports" },
    ],
    cta: "Get Started",
    featured: false,
  },
  {
    id: "advanced",
    name: "Advanced",
    desc: "For mid-size commercial teams that need broader market coverage.",
    annual: 2520,
    monthly: 210,
    save: "Save 20% vs monthly",
    feats: [
      { bold: "7", text: " dashboards included" },
      { bold: "3", text: " user seats" },
      { bold: "Extra chart: ", text: "$375", boldEnd: true },
      { text: "Extra user: $900/year" },
      { text: "Max 2 installments" },
      { text: "Mobile app access" },
      { text: "PDF & Excel exports" },
    ],
    cta: "Get Advanced",
    featured: false,
  },
  {
    id: "premium",
    name: "Premium",
    desc: "For trade associations and corporate commercial teams.",
    annual: 4500,
    monthly: 375,
    save: "Save 40% vs monthly",
    feats: [
      { bold: "15", text: " dashboards included" },
      { bold: "5", text: " user seats" },
      { bold: "Extra chart: ", text: "$300", boldEnd: true },
      { text: "Extra user: $1,100/year" },
      { text: "Max 3 installments" },
      { text: "Mobile app access" },
      { text: "PDF & Excel exports" },
      { text: "Dedicated onboarding" },
      { text: "Co-branded dashboard option" },
    ],
    cta: "Get Premium",
    featured: true,
  },
  {
    id: "titanium",
    name: "Titanium",
    desc: "For large corporations, governments and trade associations.",
    annual: 6750,
    monthly: 563,
    save: "Save 35% vs monthly",
    feats: [
      { bold: "25", text: " dashboards included" },
      { bold: "8", text: " user seats" },
      { bold: "Extra chart: ", text: "$270", boldEnd: true },
      { text: "Extra user: $1,000/year" },
      { text: "Max 4 installments" },
      { text: "Mobile app access" },
      { text: "PDF & Excel exports" },
      { text: "Custom PowerBI dashboards" },
      { text: "Dedicated SLA & account manager" },
    ],
    cta: "Talk to Sales",
    featured: false,
  },
];

export const faqData: FaqItem[] = [
  { q: "Is the data official or estimated?", a: "Official data sourced from customs agencies, ports, and government trade bodies. Each dashboard displays its source. We never publish estimates as facts." },
  { q: "Can I switch plans later?", a: "Yes. You can upgrade at any time — we prorate the remaining period. Downgrades apply at the next renewal date." },
  { q: "How many users can I add?", a: "Basic: 1 · Advanced: 3 · Premium: 5 · Titanium: 8. Additional seats cost $800–$1,100/year depending on your plan." },
  { q: "Can I embed dashboards on my website?", a: "Yes. All plans include an embed URL. Premium and Titanium plans allow co-branded dashboards with your own identity and logo." },
  { q: "What if the industry I need isn't listed?", a: "Our PowerBI Solutions team builds fully custom dashboards with brand identity and tailored filters. Contact sales for a proposal." },
  { q: "Can I pay in installments?", a: "Yes: Basic 1, Advanced 2, Premium 3, Titanium up to 4 installments. Bank wire transfer receives an additional 3% discount." },
  { q: "Is there a free trial?", a: "Yes — registering for free gives immediate access to 2 dashboards of your choice. No credit card required." },
];
